version: "3"
services:
  club_app: &app
    image: ghcr.io/therapytribe/_therapytribe:${GITHUB_SHA:-latest}
    command: make docker-run-production
    container_name: club_app
    environment:
      - MODE=production
      - PYTHONUNBUFFERED=1
      - DEBUG=false
      - APP_HOST=https://therapytribe.club
      - MEDIA_UPLOAD_URL=https://media.therapytribe.club/upload/
      - POSTGRES_DB=therapytribe_club
      - POSTGRES_USER=therapytribeclub
      - POSTGRES_PASSWORD=therapytribeclub
      - POSTGRES_HOST=postgres
      - REDIS_DB=0
      - REDIS_HOST=redis
      - VIRTUAL_HOST=therapytribe.club,www.therapytribe.club
      - VIRTUAL_PORT=8814
      - VIRTUAL_PATH=/
      #- EMAIL_HOST
      #- EMAIL_PORT
      #- DEFAULT_FROM_EMAIL
    env_file:
      - club/.env
    restart: always
    volumes:
      - ./frontend/static:/tmp/static
      - ./gdpr/downloads:/app/gdpr/downloads
    depends_on:
      - postgres
      - redis
      - queue
    ports:
      - "127.0.0.1:8814:8814"
    networks:
      - front
      - club

  queue:
    <<: *app
    command: make docker-run-queue
    container_name: club_queue
    depends_on:
      - postgres
      - redis
    ports: []
    networks:
    - club  

  bot:
    <<: *app
    command: make docker-run-bot
    container_name: club_bot
    environment:
      - APP_HOST=https://therapytribe.club
      - POSTGRES_DB=therapytribe_club
      - POSTGRES_USER=therapytribeclub
      - POSTGRES_PASSWORD=therapytribeclub
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - REDIS_DB=0
      - VIRTUAL_HOST=therapytribe.club
      - VIRTUAL_PATH=/telegram/webhook/
      - VIRTUAL_PORT=8816
    depends_on:
      - club_app
      - postgres
      - redis
    ports:
      - "8816:8816"
    networks:
      - club

  cron:
    <<: *app
    command: make docker-run-cron
    container_name: club_cron
    depends_on:
      - club_app
      - postgres
      - redis
    ports: []
    # networks:
    #   - club

  postgres:
    image: postgres:11 #12
    container_name: club_postgres
    restart: always
    environment:
      POSTGRES_USER: therapytribeclub
      POSTGRES_PASSWORD: therapytribeclub
      POSTGRES_DB: therapytribe_club
    volumes:
      - /root/pgdata:/var/lib/postgresql/data:rw
    ports:
      - "127.0.0.1:54333:5432"
    networks:
    - club

  redis:
    image: redis:alpine
    container_name: club_redis
    restart: always
    environment:
      - ALLOW_EMPTY_PASSWORD=yes
    networks:
      - club
  
  pgbackups:
  image: prodrigestivill/postgres-backup-local
  restart: always
  volumes:
    - /root/backup/therapytribe/pgdata:/backups
  links:
    - postgres
  depends_on:
    - postgres
  environment:
    - POSTGRES_HOST=postgres
    - POSTGRES_DB=therapytribe_club
    - POSTGRES_USER=therapytribeclub
    - POSTGRES_PASSWORD=therapytribeclub
    - POSTGRES_EXTRA_OPTS=-Z6 --schema=public --blobs
    - SCHEDULE=@weekly
    - BACKUP_KEEP_DAYS=7
    - BACKUP_KEEP_WEEKS=4
    - BACKUP_KEEP_MONTHS=6
    - HEALTHCHECK_PORT=8080
  networks:
    - club 

  networks:
    front:
      name: pmi_network
    club:
      name: club_network
